-- CAPTURE — Weekly conversation analytics (Standard tier).
--
-- Founder request 2026-08-23: build the "weekly/monthly AI analytics of
-- conversations surfacing trends, asks and opportunities" feature that
-- plans.has_analytics already promises on the paywall comparison table
-- but had no real generation behind it (PLANS.md 5.6 explicitly scoped
-- this out of the DEV-22 billing build). Descriptive, not predictive —
-- surfaces real recurring patterns from real conversations, never a
-- forecast, per PLANS.md's V1 guardrail against "advanced predictive
-- analytics."

create table conversation_analytics (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references businesses(id) on delete cascade,
  period_start timestamptz not null,
  period_end timestamptz not null,
  conversation_count integer not null,
  -- Each jsonb column is an array of small objects/strings — see
  -- lib/analytics/generate-conversation-analytics.ts's schema for the
  -- exact shape. Kept as jsonb rather than normalized tables: this is a
  -- generated snapshot regenerated fresh each period, never edited in
  -- place, so relational structure buys nothing here.
  recurring_asks jsonb not null default '[]'::jsonb,
  escalation_themes jsonb not null default '[]'::jsonb,
  knowledge_gaps jsonb not null default '[]'::jsonb,
  generated_at timestamptz not null default now(),
  unique (business_id, period_start)
);

comment on table conversation_analytics is 'One row per business per analytics period (weekly), regenerated by api/cron/conversation-analytics. unique(business_id, period_start) makes the cron job idempotent against a redelivered/re-triggered run.';

create index conversation_analytics_business_id_idx on conversation_analytics (business_id, period_start desc);

alter table conversation_analytics enable row level security;

-- Read-only for the business's own members/platform_admins — same pattern
-- as payments/escalation_notifications (DEV-22). Written only by the cron
-- route's service-role client, which bypasses RLS, so no insert/update
-- policy is needed here.
create policy conversation_analytics_select on conversation_analytics
  for select to authenticated using (internal.is_business_member(business_id));
